import { Lato, Raleway } from 'next/font/google'
import './globals.css'
import Providers from './Providers'

const lato = Lato({
  variable: '--font-lato',
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin']
})

const raleway = Raleway({
  variable: '--font-raleway',
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Free-Shop',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html
      lang='en'
      data-arp=''
      className={`${lato.variable} ${raleway.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col loto'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
